name: Local Actions - Market Scorer

on: [push, pull_request]

env:
  NPROC: 4

jobs:
  test:
    runs-on: [self-hosted, linux]
    container:
      image: dyeosvaldoperalta/marketscorer:1.1

    steps:
      - name: â¬‡ï¸ Clonar cÃ³digo del repositorio
        uses: actions/checkout@v4

      - name: ğŸ§ª Ejecutar pruebas
        run: python tests/run_tests.py
