name: Tests y Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: dyeosvaldoperalta/marketscorer:1.1

    steps:
      - name: â¬‡ï¸ Clonar repositorio
        uses: actions/checkout@v4

      - name: ğŸ§ª Ejecutar pruebas y coverage
        run: |
          mkdir -p htmlcov/reports
          python tests/run_tests.py indicators/

      - name: ğŸ“ Subir reportes como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-test-reports
          path: htmlcov/reports/
